server:
  port: 8762
#  context-path: /member
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/
spring:
  application:
    name: member

  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    database: 8
    password:
    jedis:
      pool:
        # 最大连接数
        max-active: 8
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        # 最大空闲
        max-idle: 8
        # 最小空闲
        min-idle: 0
