server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/
spring:
  application:
    name: web

feign:
  hystrix:
    enabled: true

# 暴露全部的监控信息(Dashboard使用)
management:
  endpoints:
    web:
      exposure:
        include: "*"

#ribbon:
#  eureka:
#    enabled: true
