server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/
spring:
  application:
    name: web

feign:
  hystrix:
    enabled: true

#ribbon:
#  eureka:
#    enabled: true
